use std::collections::HashMap;
use std::process::{Command, Child, Stdio};
use std::sync::Mutex;
use serde::{Deserialize, Serialize};
use base64::{engine::general_purpose, Engine as _};
use tauri::State;

struct AppState {
    jobs: Mutex<HashMap<String, Child>>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct StartJobOptions {
    output: Option<String>,
    no_audio: bool,
    no_clip: bool,
    mode: String, // "plan", "apply", or "process"
}

#[tauri::command]
fn start_job(
    input_path: String,
    options: StartJobOptions,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let mut args = vec![options.mode.clone(), input_path.clone()];
    
    if let Some(out) = &options.output {
        args.push("--output".to_string());
        args.push(out.clone());
    }
    
    if options.no_audio {
        args.push("--no-audio".to_string());
    }
    if options.no_clip {
        args.push("--no-clip".to_string());
    }

    let child = Command::new("pureframe")
        .args(&args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("Failed to start pureframe: {}", e))?;

    let job_id = uuid::Uuid::new_v4().to_string();
    let mut jobs = state.jobs.lock().unwrap();
    jobs.insert(job_id.clone(), child);

    Ok(job_id)
}

#[tauri::command]
fn cancel_job(id: String, state: State<'_, AppState>) -> Result<(), String> {
    let mut jobs = state.jobs.lock().unwrap();
    if let Some(mut child) = jobs.remove(&id) {
        let _ = child.kill();
    }
    Ok(())
}

#[tauri::command]
fn load_plan(path: String) -> Result<String, String> {
    std::fs::read_to_string(path).map_err(|e| e.to_string())
}

#[tauri::command]
fn save_plan(path: String, plan_json: String) -> Result<(), String> {
    std::fs::write(path, plan_json).map_err(|e| e.to_string())
}

#[tauri::command]
fn extract_thumbnail(video_path: String, frame_idx: usize) -> Result<String, String> {
    // ffmpeg -i input.mp4 -vf "select=eq(n\,100)" -vframes 1 -f image2pipe -vcodec mjpeg -
    let output = Command::new("ffmpeg")
        .args(&[
            "-i", &video_path,
            "-vf", &format!("select=eq(n\\,{})", frame_idx),
            "-vframes", "1",
            "-f", "image2pipe",
            "-vcodec", "mjpeg",
            "-"
        ])
        .output()
        .map_err(|e| e.to_string())?;

    if output.stdout.is_empty() {
        return Err("No frame data generated by ffmpeg".to_string());
    }

    let b64 = general_purpose::STANDARD.encode(&output.stdout);
    Ok(format!("data:image/jpeg;base64,{}", b64))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AppState {
            jobs: Mutex::new(HashMap::new()),
        })
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            start_job,
            cancel_job,
            load_plan,
            save_plan,
            extract_thumbnail
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
